# Generated by Django 3.1.7 on 2021-02-23 01:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PacientesBD',
            fields=[
                ('rut', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=25)),
                ('apellido', models.CharField(max_length=25)),
                ('email', models.CharField(max_length=50)),
                ('tutor', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=50)),
                ('enfermedades', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ExamenesBD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orina', models.IntegerField()),
                ('glucosa', models.IntegerField()),
                ('colesterol', models.IntegerField()),
                ('triglicerido', models.IntegerField()),
                ('bilirrubina', models.IntegerField()),
                ('fecha', models.DateField()),
                ('rutdb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formulariosBD.pacientesbd')),
            ],
        ),
    ]
